// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARL2LUHtN7V0UyIWE2Z5WcsHWpygM152A',
    appId: '1:737157204775:web:3e960a6378dc3ef7ffb702',
    messagingSenderId: '737157204775',
    projectId: 'hotelio-126c2',
    authDomain: 'hotelio-126c2.firebaseapp.com',
    storageBucket: 'hotelio-126c2.appspot.com',
    measurementId: 'G-2G5BBPMW45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC24daW0fDFBVDRZBdeBRdaRK1SWFOZgYY',
    appId: '1:737157204775:android:e6d9b865e926fb39ffb702',
    messagingSenderId: '737157204775',
    projectId: 'hotelio-126c2',
    storageBucket: 'hotelio-126c2.appspot.com',
  );

}